FROM quay.io/fedora/fedora-coreos:stable
RUN rpm-ostree override replace https://bodhi.fedoraproject.org/updates/FEDORA-2024-d5e5296648 && \
    #workaround for: https://github.com/coreos/layering-examples/issues/49
    rpm --reinstall https://kojipkgs.fedoraproject.org//packages/systemd/255.4/1.fc40/x86_64/systemd-255.4-1.fc40.x86_64.rpm && \
    #https://coreos.github.io/rpm-ostree/architecture-core/#content-in-var
    rm -rf /var/lock /var/mail /var/lib/ /var/log /var/run && \
    ostree container commit
