FROM quay.io/fedora/fedora-coreos:stable

# Setup the podman-next copr repo
# Note: This might need to be updated from time to time to the latest GPG key.
# The repo config itself is release agnotic but the GPG key might change.
COPY rhcontainerbot-podman-next-fedora.repo /etc/yum.repos.d/
COPY rhcontainerbot-podman-next-fedora.gpg /etc/pki/rpm-gpg/

# Replace aardvark-dns, conmon, crun, netavark, podman, containers-common
# Remove moby-engine, containerd, runc
# Note: Currently does not result in a size reduction for the container image
RUN rpm-ostree override replace --experimental --freeze \
        --from repo="copr:copr.fedorainfracloud.org:rhcontainerbot:podman-next" \
        aardvark-dns conmon crun netavark podman containers-common containers-common-extra && \
    rpm-ostree override remove moby-engine containerd runc && \
    rpm-ostree cleanup -m && \
    ostree container commit
