# This example uses rpm-ostree's cliwrap to allow dracut to run on the container and generate an initramfs.
FROM quay.io/fedora/fedora-coreos:stable
# Enable cliwrap.
RUN rpm-ostree cliwrap install-to-root /
# Replace the kernel, kernel-core and kernel-modules packages.
RUN rpm-ostree override replace https://kojipkgs.fedoraproject.org//packages/kernel/6.0.10/300.fc37/x86_64/kernel-6.0.10-300.fc37.x86_64.rpm \
    https://kojipkgs.fedoraproject.org//packages/kernel/6.0.10/300.fc37/x86_64/kernel-core-6.0.10-300.fc37.x86_64.rpm \
    https://kojipkgs.fedoraproject.org//packages/kernel/6.0.10/300.fc37/x86_64/kernel-modules-6.0.10-300.fc37.x86_64.rpm && \
    ostree container commit
