# Change a SELinux boolean. A conflict between overlayfs semantics
# and libselinux existed before fedora 37. This examples shows that
# selinux booleans can now be changed correctly as part of the build.
# https://github.com/SELinuxProject/selinux/pull/342
FROM quay.io/fedora/fedora-coreos:stable

RUN setsebool -P -N container_manage_cgroup 1
